version: '3'
services:
  mysql:
    build:
      context: .
      dockerfile: dockerfile.mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tasks_manager
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      TZ: "UTC"
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq: 
    image: "rabbitmq:management"
    ports: 
      - "5672:5672" # Port for communication
      - "15672:15672" # Port for management interface
    environment: 
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

volumes:
  mysql_data:
