// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: tasks.proto

package tasks

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TaskService_AddTask_FullMethodName             = "/TaskService/AddTask"
	TaskService_MarkTaskAsCompleted_FullMethodName = "/TaskService/MarkTaskAsCompleted"
	TaskService_ListTaks_FullMethodName            = "/TaskService/listTaks"
)

// TaskServiceClient is the client API for TaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskServiceClient interface {
	AddTask(ctx context.Context, in *Tasks, opts ...grpc.CallOption) (*Empty, error)
	MarkTaskAsCompleted(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	ListTaks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (TaskService_ListTaksClient, error)
}

type taskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskServiceClient(cc grpc.ClientConnInterface) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) AddTask(ctx context.Context, in *Tasks, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, TaskService_AddTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) MarkTaskAsCompleted(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, TaskService_MarkTaskAsCompleted_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ListTaks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (TaskService_ListTaksClient, error) {
	stream, err := c.cc.NewStream(ctx, &TaskService_ServiceDesc.Streams[0], TaskService_ListTaks_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &taskServiceListTaksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TaskService_ListTaksClient interface {
	Recv() (*Tasks, error)
	grpc.ClientStream
}

type taskServiceListTaksClient struct {
	grpc.ClientStream
}

func (x *taskServiceListTaksClient) Recv() (*Tasks, error) {
	m := new(Tasks)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TaskServiceServer is the server API for TaskService service.
// All implementations must embed UnimplementedTaskServiceServer
// for forward compatibility
type TaskServiceServer interface {
	AddTask(context.Context, *Tasks) (*Empty, error)
	MarkTaskAsCompleted(context.Context, *TaskRequest) (*TaskResponse, error)
	ListTaks(context.Context, *Empty) error
}

// UnimplementedTaskServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTaskServiceServer struct {
}

func (UnimplementedTaskServiceServer) AddTask(context.Context, *Tasks) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTask not implemented")
}
func (UnimplementedTaskServiceServer) MarkTaskAsCompleted(context.Context, *TaskRequest) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkTaskAsCompleted not implemented")
}
func (UnimplementedTaskServiceServer) ListTaks(context.Context, *Empty) error {
	return status.Errorf(codes.Unimplemented, "method ListTaks not implemented")
}
func (UnimplementedTaskServiceServer) mustEmbedUnimplementedTaskServiceServer() {}

// UnsafeTaskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskServiceServer will
// result in compilation errors.
type UnsafeTaskServiceServer interface {
	mustEmbedUnimplementedTaskServiceServer()
}

func RegisterTaskServiceServer(s grpc.ServiceRegistrar, srv TaskServiceServer) {
	s.RegisterService(&TaskService_ServiceDesc, srv)
}

func _TaskService_AddTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Tasks)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).AddTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_AddTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).AddTask(ctx, req.(*Tasks))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_MarkTaskAsCompleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).MarkTaskAsCompleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_MarkTaskAsCompleted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).MarkTaskAsCompleted(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

//func _TaskService_ListTaks_Handler(srv interface{}, stream grpc.ServerStream) error {
//	m := new(Empty)
//	if err := stream.RecvMsg(m); err != nil {
//		return err
//	}
	//return srv.(TaskServiceServer).ListTaks(m, &taskServiceListTaksServer{stream})
//}

type TaskService_ListTaksServer interface {
	Send(*Tasks) error
	grpc.ServerStream
}

type taskServiceListTaksServer struct {
	grpc.ServerStream
}

func (x *taskServiceListTaksServer) Send(m *Tasks) error {
	return x.ServerStream.SendMsg(m)
}

// TaskService_ServiceDesc is the grpc.ServiceDesc for TaskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTask",
			Handler:    _TaskService_AddTask_Handler,
		},
		{
			MethodName: "MarkTaskAsCompleted",
			Handler:    _TaskService_MarkTaskAsCompleted_Handler,
		},
	},
	//Streams: []grpc.StreamDesc{
	//	{
	//		StreamName:    "listTaks",
	//		Handler:       _TaskService_ListTaks_Handler,
	//		ServerStreams: true,
	//	},
	//},
	Metadata: "tasks.proto",
}
